name: choosr
description: Randomize picker for victims of analysis paralysis
version: 1.0.0+1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: any
  sembast: ^1.15.1
  path_provider: ^0.5.0+1
  # Used for BLoC state management
  flutter_bloc: ^0.21.0
  equatable: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Thin.ttf
          style: italic
