name: dcydr
description: Randomized picker for victims of analysis paralysis
version: 1.0.0+1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: any
  flat_icons_flutter: ^1.0.2
  sembast: ^1.15.1
  path_provider: ^0.5.0+1
  # bloc
  bloc: ^2.0.0
  flutter_bloc: ^2.0.0
  equatable: ^1.0.0
  meta: ^1.1.6
  gradient_app_bar: ^0.0.1
  gradient_text: ^1.0.2
  # logger
  logger: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: GothamPro
      fonts:
        - asset: fonts/GothamPro-Regular.otf
